### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by shadisky** [sizuhiko/Bdd#10]
Thank you for sharing this BDD framework for CakePHP.

I cant seem to get it running. When I reach the Configuration section I get an error when executing the cake command:

$ lib/Cake/Console/cake Bdd.init
Error: Plugin Bdd could not be found.
#0 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(365): CakePlugin::path('Bdd')
#1 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(226): App::pluginPath('Bdd')
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(543): App::path('Console/Command',

 'Bdd')
#3 [internal function]: App::load('InitShell')
#4 [internal function]: spl_autoload_call('InitShell')
#5 C:\xampp\htdocs\cake\lib\Cake\Console\ShellDispatcher.php(240): class_exists(

'InitShell')
#6 C:\xampp\htdocs\cake\lib\Cake\Console\ShellDispatcher.php(190): ShellDispatch

er->_getShell('Bdd.init')
#7 C:\xampp\htdocs\cake\lib\Cake\Console\ShellDispatcher.php(68): ShellDispatche

r->dispatch()
#8 C:\xampp\htdocs\cake\lib\Cake\Console\cake.php(44): ShellDispatcher::run(Arra

y)
#9 {main}

I have followed all the previous steps in the tutorial successfully but keep getting this error.

Your help is highly appreciated.

Thanks,
Shadi

**Comment by sizuhiko** [comment]
Sorry, my response is too late.
Because, I'm busy.
I will be able to check your problem on next week.

Please, reply your configuration
- PHP version
- CakePHP version

**Comment by shadisky** [comment]
Hi again,
Thanks for your reply.

PHP version: 5.4.7 (included in XAMPP 1.8.1)
CakePHP version: 2.3.1

I look forward to your response.

**Comment by sizuhiko** [comment]
Hi shadiissa.
Please check your `app/Config/bootstrap.php`.
I think that you forgot to add settings following:
<code>
CakePlugin::load('Bdd');
</code>

The line is required for using CakePHP plugin.

And add following if you installed for using composer/installer:
<code>
require dirname(dirname(**FILE**)).DS.'Vendor/autoload.php';
</code>
