### ISSUE TITLE
Testing when having Session in a Model 

### ISSUE THREAD

**Issue by sela** [sizuhiko/Bdd#19]
I use a session in a model and it doesn't work when
Console/cake Bdd.story
I read in Cake 3 (I use 2) to use --stderr I think they mention it related to PHPUnit. What is the way to test it using this plugin if there is a way?

**Comment by sizuhiko** [comment]
Sorry, late response.

I think you should create session table to database for testing, before run Bdd.story.

**Comment by sela** [comment]
Thanks @sizuhiko I moved out the usage of session at the end. So I'll close this ticket. Nice to meet you at CakeFest.
