### ISSUE TITLE
Console_CommandLine_Result、Hamcrestをロードできない？

### ISSUE THREAD

**Issue by kaz29** [sizuhiko/Bdd#2]
ブログの記事(http://my.opera.com/sizuhiko/blog/2012/08/19/bdd-plugin-for-cakephp2)を参考にサンプルアプリを試してみたのですが、２点うまく動かないところがありました。

一点目は"Console/CommandLine/Result.php" が上手くロードできない問題で以下の修正で解決しました。
https://github.com/kaz29/Bdd/commit/b2e854dd96732e1524e4f0a61debbfcd81647053

二点目は、手元の環境ではHamcrestがロードでませんでした。composerをあまり使った事が無いのでよくわからないのですが、composer.jsonでautoloadの設定を指定している様にみえるのにロードできなかったので、 vendor/composer/include_paths.phpを以下の様に直してとりあえず動かしています。

<?php

// include_paths.php generated by Composer

$vendorDir = dirname(**DIR**);
$baseDir = dirname($vendorDir);

return array(
$vendorDir . '/pear-pear.php.net/Console_CommandLine/',
$vendorDir . '/pear-pear.phpunit.de/Object_Freezer/',
$vendorDir . '/hamcrest/Hamcrest/Hamcrest-1.1.0/', // => 追加
);

アドバイスお願いしますー！

**Comment by sizuhiko** [comment]
Console/CommandLineの件は、ローカルのPEARでも入っていたので、問題がなかったようです。すみません。PRもらえると嬉しいです。

hamcrestは`vendor/composer/autoload_classmap.php`にパス追加されているはずなのですが、再度確認してみます。

**Comment by sizuhiko** [comment]
hamcrestがinclude_pathなのかclassmapなのかで違うのかもしれないので、
https://gist.github.com/3633857
でもあるように、composer.jsonでの指定方法をinclude_pathに変更してみます。

**Comment by sizuhiko** [comment]
developブランチにhamcrestのrepository記述を変更したものを入れましたので、これで試してもらって良いでしょうか？
vendorディレクトリを削除して、`php composer.phar install --dev`で更新できると思います。
サンプルのspec`./spec/matchers.spec.php`が1つ失敗しますが、これは無視しておいてください。

**Comment by kaz29** [comment]
これ https://gist.github.com/3633857 だとなんか上手く動かなかったです...。
include_pathに変更したら上手く行きました〜。一応PR投げときます、

**Comment by sizuhiko** [comment]
私の環境だとdevelopブランチにあるように、autoloadセクションを

<pre>
"autoload": {
    "psr-0": { "Hamcrest_": "Hamcrest-1.1.0/" },
    "files": ["Hamcrest-1.1.0/Hamcrest/Hamcrest.php"]
}
</pre>

のようにしても動作したのですが、classmapのままでないと動作しないという理解で良いでしょうか？

**Comment by kaz29** [comment]
あれ？動かなかったと思うんだけど...。もう一回試してみます。

**Comment by kaz29** [comment]
any() の多重定義エラーが出ますね。
そしてclassmapにするとちゃんと動く...、何だろこの現象。

PHP Fatal error:  Cannot redeclare any() (previously declared in /Users/kaz/srv/httpd/bddtest/application/plugins/Bdd/vendor/hamcrest/Hamcrest/Hamcrest-1.1.0/Hamcrest/Hamcrest.php:385) in /Users/kaz/srv/pear/share/pear/PHPUnit/Framework/Assert/Functions.php on line 56

もう少し調べてみますが、何か気づいた点あれば教えてください！

**Comment by sizuhiko** [comment]
anyがSpec4PHPとPHPUnit両方で定義されていて、Spec4PHP側では`function_exists('any')`しているので、include_pathとclassmapの読み込み順の中でSpec4PHP側が後になると、多重定義エラーが出ないという事なのだと思います(PHPUnit側には多重定義防止策がない)。

また、autoloadの書き方について、include_pathとclassmapの両方にパス指定があるとダメなのかと思いきや、PEARから取り込んでいるConsole/CommandLineがinclude_pathとclassmap両方にパス指定が入るようになっている(autoloadが自動生成されている)ので、Composerとしては問題ないようです。このあたりは私もComposerを理解しきれていないと感じました。
いただいたPRをマージしたいと思います。
ありがとうございました。

**Comment by kaz29** [comment]
なるほど〜、僕も全然Composer理解出来てないです :cry: 
マージありがとうございました！
